### ISSUE TITLE
Support for specifying table name at runtime

### ISSUE THREAD

**Issue by val1tine** [cashapp/tempest#128]
There does not seem to be a way to specify a table name except via. annotations that cannot be modified at runtime.  We have different table names in different environments (dev, qa, prod) and would like to be able to set the table name at runtime via e.g., a configuration file.

**Comment by zhxnlai** [comment]
Tempest uses AWS SDK under the hood. Here is how to customize table names: 
```kotlin
  fun logicalDbOptionalConfiguration() {
    val client = AmazonDynamoDBClientBuilder.standard().build()
    val mapperConfig = DynamoDBMapperConfig.builder()
      .withTableNameOverride(null) // <-- Set this
      .build()
    val mapper = DynamoDBMapper(client, mapperConfig)
    val db: MusicDb = LogicalDb(mapper)
  }
```
