### ISSUE TITLE
Support for AWS SDK 2.x

### ISSUE THREAD

**Issue by ansman** [cashapp/tempest#23]
Currently Tempest depends on `com.amazonaws:aws-java-sdk-dynamodb` which is the old AWS SDK for Java. There is a [new SDK][https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html] and it would be great if Tempest could support it (perhaps along side with the old SDK even)

**Comment by zhxnlai** [comment]
Thanks! That sounds like a good idea. I will look into it.

**Comment by ansman** [comment]
Thank you! I talked to Jesse a bit and since the 2.x SDK also has a mapper it might not be that difficult.

**Comment by zhxnlai** [comment]
Released "app.cash.tempest:tempest2:1.3.0" for SDK 2.x.
