### ISSUE TITLE
Setting attributes with `is_` prefixed in the naming causes IllegalArgumentException

### ISSUE THREAD

**Issue by foosbars** [cashapp/tempest#53]
Received the following error when attempting to add a field with `is_` prefixed in the naming. 

```
[Guice/ErrorInCustomProvider]: IllegalArgumentException: Expect is_some_field, required by class SomeEntity, to be declared in class SomeItem. Use @Transient to exclude it.
   ....
```

**Comment by zhxnlai** [comment]
I was able to reproduce this using an example with a field named `is_enabled`.
<img width="639" alt="Screen Shot 2021-05-21 at 5 50 09 PM" src="https://user-images.githubusercontent.com/4694896/119209859-f5977200-ba5d-11eb-897a-a5eee187915c.png">

It looks like DynamoDBMapper, which uses Java Bean under the hood, interprets `is_some_field` as `_some_field`.
According to [this](https://stackoverflow.com/questions/799280/valid-javabeans-names-for-boolean-getter-methods), this is not a bug but an implicit feature of JavaBeans specification.
