### ISSUE TITLE
Error in Testing Documentation

### ISSUE THREAD

**Issue by chris-ryan-square** [cashapp/tempest#56]
On this page: https://cashapp.github.io/tempest/guide/testing/ there is this line of code:

`.addTable(TestTable.create<MusicItem>())`

I think it needs the table name specified as well?

`.addTable(TestTable.create(MusicItem.TABLE_NAME, MusicItem::class.java))`

**Comment by zhxnlai** [comment]
This was fixed in https://github.com/cashapp/tempest/pull/47. I will release it today.
