### ISSUE TITLE
Migration guide from Tempest v1 to v2

### ISSUE THREAD

**Issue by alvinsee** [cashapp/tempest#64]
It appears that there are some breaking changes with dynamodb v2 apis that led to the same breaking changes in tempest v2. It would be beneficial to have a migration guide for customers on v1 to help them move over to v2.

**Comment by peckb1** [comment]
I recently upgraded, and created an upgrade guide with the steps needed.

https://github.com/cashapp/tempest/blob/master/docs/guide/v2_upgrade_guide.md
